### ISSUE TITLE
FATAL EXCEPTION :  Unable to start receiver ir.cafebazaar.poolakey.receiver.BillingReceiver

### ISSUE THREAD

**Issue by ali-katayoni** [cafebazaar/flutter_poolakey#21]
با سلام.
خطای زیر در زمان فراخوانی متد connect مشاهده شد و باعث کرش کردن و بسته شدن اپ شد. اهمیتی ندارد این متد چه زمانی و به چه طریقی فراخوانی شود. فراخوانی متد connect بازار در هر زمانی و شرایطی با این خطا مواجه خواهد شد : 

Syncing files to device SM A525F...
D/AndroidRuntime(20899): Shutting down VM
E/AndroidRuntime(20899): FATAL EXCEPTION: main
E/AndroidRuntime(20899): Process:….., PID: ….
E/AndroidRuntime(20899): java.lang.RuntimeException: Unable to start receiver ir.cafebazaar.poolakey.receiver.BillingReceiver: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(20899): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4903)
E/AndroidRuntime(20899): 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
E/AndroidRuntime(20899): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2420)
E/AndroidRuntime(20899): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(20899): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(20899): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(20899): 	at android.app.ActivityThread.main(ActivityThread.java:8762)
E/AndroidRuntime(20899): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20899): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/AndroidRuntime(20899): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(20899): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(20899): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/AndroidRuntime(20899): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:272)
E/AndroidRuntime(20899): 	at ir.cafebazaar.flutter_poolakey.FlutterPoolakeyPlugin$connect$1$1.invoke(FlutterPoolakeyPlugin.kt:114)
E/AndroidRuntime(20899): 	at ir.cafebazaar.flutter_poolakey.FlutterPoolakeyPlugin$connect$1$1.invoke(FlutterPoolakeyPlugin.kt:113)
E/AndroidRuntime(20899): 	at ir.cafebazaar.poolakey.callback.ConnectionCallback$connectionSucceed$2.invoke(ConnectionCallback.kt:19)
E/AndroidRuntime(20899): 	at ir.cafebazaar.poolakey.callback.ConnectionCallback$connectionSucceed$2.invoke(ConnectionCallback.kt:6)
E/AndroidRuntime(20899): 	at ir.cafebazaar.poolakey.billing.connection.ReceiverBillingConnection.onBillingSupportActionReceived(ReceiverBillingConnection.kt:428)
E/AndroidRuntime(20899): 	at ir.cafebazaar.poolakey.billing.connection.ReceiverBillingConnection.onActionReceived(ReceiverBillingConnection.kt:131)
E/AndroidRuntime(20899): 	at ir.cafebazaar.poolakey.billing.connection.ReceiverBillingConnection.access$onActionReceived(ReceiverBillingConnection.kt:47)
E/AndroidRuntime(20899): 	at ir.cafebazaar.poolakey.billing.connection.ReceiverBillingConnection$createReceiverConnection$1.onNewBroadcastReceived(ReceiverBillingConnection.kt:122)
E/AndroidRuntime(20899): 	at ir.cafebazaar.poolakey.receiver.BillingReceiver.notifyObservers(BillingReceiver.kt:23)
E/AndroidRuntime(20899): 	at ir.cafebazaar.poolakey.receiver.BillingReceiver.onReceive(BillingReceiver.kt:16)
E/AndroidRuntime(20899): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4894)
E/AndroidRuntime(20899): 	... 9 more
I/Process (20899): Sending signal. PID: 20899 SIG: 9
Lost connection to device.

این مشکل بر روی دستگاه Samsung A 52 با اندروید ورژن 13 و One UI version 5.1 وجود دارد.
بر روی برخی دستگاه های با ورژن قدیمی اندروید بررسی شد و مشکل فوق وجود نداشت.

ورژن فلاتر : 3.19.0
ورژن پولکی : 2.2.0

درضمن، هشدار زیر هم در ورژن فوق نمایش داده میشود.

AppData\Local\Pub\Cache\hosted\pub.dev\flutter_poolakey-2.2.0\android\src\main\kotlin\ir\cafebazaar\flutter_poolakey\PaymentActivity.kt:41:13: warning: 'when' is exhaustive so 'else' is redundant here
            else -> throw InvalidParameterException("Undefined command: $command")
            ^

**Comment by mj-yousefi** [comment]
با سلام.
من هم در ورژن یکسان به همین مشکل تو بعضی دیوایس‌ها برخوردم (با سایر ورژن‌ها امتحان نکردم). ورژن فلاتر : 3.19.0 و ورژن پولکی : 2.2.0. این مورد رو در چند گوشی مشاهده کردم. 

یک راه هم برای شبیه‌سازی این خطا در سایر گوشی‌ها وجود داره به این ترتیب که ابتدا برنامه‌ی خودتون را باز کنید، بعد وارد اپلیکیشن بازار بشید و اون رو ببنید. یا بعد از از این که وارد بازار شدید، مجدد وارد اپ خودتون بشید و سپس بازار رو از recent اپلیکیشن‌ها ببنید. احتمال میدم تو این حالت دیسکانکت شدن و کانکت شدن مجدد به بازار اتفاق میفته و خطا رخ میده.

طبق بررسی من در `FlutterPoolakeyPlugin.kt` در بخش زیر خطا رخ میده:

```
private fun connect(inAppBillingKey: String?, result: Result) {
        val securityCheck = if (inAppBillingKey != null) {
            SecurityCheck.Enable(rsaPublicKey = inAppBillingKey)
        } else {
            SecurityCheck.Disable
        }
        val paymentConfiguration = PaymentConfiguration(localSecurityCheck = securityCheck)

        payment = Payment(context = requireActivity, config = paymentConfiguration)

        paymentConnection = payment.connect {
            connectionSucceed {
                result.success(true)
            }
            connectionFailed {
                result.error("CONNECTION_HAS_FAILED", it.toString(), null)
            }
            disconnected {
                channel.invokeMethod("disconnected", null)
            }
        }
    }
```

و `result.success`  اشتباها کال میشه.

چون برای من فورس بود، این بخش رو عوض کردم و مشکلم حل شد. با چند دیوایس تست کردم. کدی که تغییر دادم رو تو برنچ مجزا کامیت کردم و [اینجا](https://github.com/cafebazaar/flutter_poolakey/pull/23) PL دادم. امیدوارم به حل این مشکل کمک کنه.

**Comment by AminFeizi** [comment]
این خیلی بده که بازار آپدیتی نمیده براش تا فیکسش کنه

**Comment by Saeeed-B** [comment]
@AminFeizi تازه جالب اینجاست توی مستندات همین پکیج رو معرفی کرده ولی اصلا گردن نمیگیرن ، میگن این پیکیج  رو پشتیبانی نمیکنیم

**Comment by hosseinipour** [comment]
@Saeeed-B 
مگه میشه؟! این پکیج تو ریپازیتوری رسمی بازاره!

**Comment by nasrabadiAM** [comment]
سلام، امیدوارم خوب باشید. 
با اعمال تغییرات @mj-yousefi و ریلیز اون در نسخه آخر [2.2.0-1.0.0-alpha01](https://github.com/cafebazaar/flutter_poolakey/releases/tag/2.2.0-1.0.0-alpha01) باید این مشکل حل شده باشه، لطفا نسخه آخر رو تست کنید و اگر مشکلی بود، مجدد کامنت بزارید. 

من فعلا این issue رو میبندم.
